# Generated by Django 4.2.2 on 2023-10-18 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_System', '0002_alter_chatmessage_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyDeletedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_message_id', models.IntegerField()),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat_System.chatroom')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
