# Generated by Django 4.2.2 on 2023-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingSystem_CRUD', '0001_initial'),
        ('Registration_Login_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_events',
            field=models.ManyToManyField(blank=True, to='MeetingSystem_CRUD.event'),
        ),
    ]
