# Generated by Django 4.2.2 on 2023-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login_App', '0002_alter_profile_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden_on_search_page',
            field=models.BooleanField(default=False),
        ),
    ]
