# Generated by Django 4.2.2 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login_App', '0003_profile_is_hidden_on_search_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
